### ISSUE TITLE
Add Video Playback Speed controller

### ISSUE THREAD

**Issue by Tobibur** [dev-labs-bg/fullscreen-video-view#21]
Hello Sir,

Your library is very good. I appreciate it. I would like to know if a video playback speed controller (Like 1x,1.5x,2x..etc) can be implemented in this library. 

Thanks,
Tobibur Rahman

**Comment by slavipetrov** [comment]
Hello, Tobibur!

The feature you've requested has been added to the library. It is available only for devices with Android API 23 or above. You can see how to use it from the repository's README.
