### ISSUE TITLE
Thumbnail image

### ISSUE THREAD

**Issue by deepsheth-agile** [dev-labs-bg/fullscreen-video-view#23]
How to set thumbnail image of the video?

**Comment by omidraha** [comment]
Hi,
Thumbnail for video is Supported currently?

**Comment by slavipetrov** [comment]
Hello,

No, it's not currently supported, it is planned for the next release of the library.

**Comment by slavipetrov** [comment]
This feature is added in the latest version of the library (1.1.0).
