### ISSUE TITLE
Error in Oreo OS

### ISSUE THREAD

**Issue by bambanghariantosianturi** [dev-labs-bg/fullscreen-video-view#24]
My fullscreenview Error in OS android oreo

**Comment by slavipetrov** [comment]
Can you provide more information about the error?

**Comment by bambanghariantosianturi** [comment]
If the fullscreen button is pressed on FullscreenVideoView then our device will be error all the useless device functions

**Comment by slavipetrov** [comment]
What is the version of Android which is installed on the device?
Have you tried to run your project on several Android versions and if so is this also happening on every one of them?

**Comment by bambanghariantosianturi** [comment]
If I run it on Android version 5.1 (Lollipop) and Android version 6.0 (Marsmallow) Fullscreen Video can work well. But for android version 8.0 (Oreo) Fullscreen Video can't work.

**Comment by slavipetrov** [comment]
I've tested the application on Android 8.0 and there are no errors.

Where do you place your FullscreenVideoView in your layout files? Is it placed directly in an Activity or a Fragment or it is inside a RecyclerView Adapter or some other view?

**Comment by bambanghariantosianturi** [comment]
Sorry slavipetrov, now it's no longer an error. I am wrong in placing validation in the onConfiguration method. Now I have fixed it and I don't find any more errors.

**Comment by slavipetrov** [comment]
Okay, thank you for sharing that! I will close the issue.
