### ISSUE TITLE
How to hide the seekbar

### ISSUE THREAD

**Issue by Zakkusu** [dev-labs-bg/fullscreen-video-view#31]
Hello,  there is a way to hide the seekbar?  i want to use it a for live stream

**Comment by slavipetrov** [comment]
Hello, this functionality is not supported yet. It will be available in the new version of the library.

Do you want to just hide the SeekBar or you want to hide the buttons as well (the whole controller)?

**Comment by Zakkusu** [comment]
Just hide the SeekBar, something like that
![61245420_470662747004414_1230784485679693824_n](https://user-images.githubusercontent.com/10994056/58578438-68263c00-820e-11e9-99fe-15318a111eee.jpg)

**Comment by slavipetrov** [comment]
Hiding the SeekBar is added in the latest version of the library (1.1.0).
