### ISSUE TITLE
Setup  a SetOnErrorListener

### ISSUE THREAD

**Issue by Zakkusu** [dev-labs-bg/fullscreen-video-view#42]
Hello, there is a way to setup the setOnErrorListener? I want to know when a videoUrl is not available to hide the "loading" animation and show a message to the user. I also saw that now we can pause programmatically so it would be good to be able to play it in the same way.

![image](https://user-images.githubusercontent.com/10994056/60040629-0cb96380-967f-11e9-8f95-6507630a8ab7.png)

 PD:you've been doing a very good job, if there's any way I can support you $, let me know

**Comment by slavipetrov** [comment]
Hello,

The error listening feature has been implemented in the newest version of the library (1.1.2). You can see how to use it in the README file. Also, I've added support for playing videos programmatically.
