### ISSUE TITLE
Add media controller listener

### ISSUE THREAD

**Issue by bharathnr21** [dev-labs-bg/fullscreen-video-view#45]
Add media controller listener

**Comment by slavipetrov** [comment]
Hello, bharathnr21, what events do you want to listen for in this "media controller listener"? 

Please provide more information about your request.

**Comment by bharathnr21** [comment]
> Hello, bharathnr21, what events do you want to listen for in this "media controller listener"?
> 
> Please provide more information about your request.

Play, pause , seekbar ,forward and rewind listener.

**Comment by slavipetrov** [comment]
Hello, bharathnr21,

The new feature is added in version 1.1.3 of the library. You can see how to use it in the README.md file in the repository.

Happy coding!
