### ISSUE TITLE
Support seekTo() method

### ISSUE THREAD

**Issue by hoanglm4** [dev-labs-bg/fullscreen-video-view#48]
Hi @slavipetrov,

Can you add seekTo() method in this library ? I want go to specified time position when start FullscreenVideoView

Thanks

**Comment by slavipetrov** [comment]
Hi @hoanglm4,

The new method is introduced in the new version of the library (1.1.4). You can download and try it.

Happy coding!

**Comment by hoanglm4** [comment]
Hi @slavipetrov ,
It's great. Thank you so much
