### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by iMaks99** [dev-labs-bg/fullscreen-video-view#53]
When I turn player to landscape mode there is text like "test" or "test text"

**Comment by slavipetrov** [comment]
Hello, @iMaks99,

I have searched for strings "test" and "test text" in the project but there are no results.

Could you search in your project as well and see if the issue is coming from you?

**Comment by iMaks99** [comment]
I have searched these string too and found that in landscape mode video view doesn't fill screen fully. I mean  that some text below the video view

**Comment by slavipetrov** [comment]
Can you give me an example layout file structure, so I can reproduce the issue and see what's wrong exactly?
