### ISSUE TITLE
Couldn't change video url

### ISSUE THREAD

**Issue by PhongNgo1776** [dev-labs-bg/fullscreen-video-view#55]
Now I'm using this method to play a video: fullscreenVideoView.videoUrl().
But I would like to change to play another url. So I haven't known how to change url to play another video.
Could you help me how to change url of fullscreenVideoView?
Thanks

**Comment by slavipetrov** [comment]
Hello, @PhongNgo1776 

Do you want to change the video URL at runtime?

**Comment by PhongNgo1776** [comment]
Yes. For example: I would like to develop application about series movies: after finished watching episode 1, I click on button Next episode to watch next video on the same layout.

**Comment by slavipetrov** [comment]
Okay, I understand. I am on it!

**Comment by slavipetrov** [comment]
Changing the video URL at runtime is available at the latest version of the library (1.1.5). Check the README file for more information about using it.
