### ISSUE TITLE
Failed to resolve dependency

### ISSUE THREAD

**Issue by ManuelEMR** [dev-labs-bg/fullscreen-video-view#61]
I'm getting `Failed to resolve: bg.devlabs.fullscreenvideoview:library:1.1.3`

When trying to download this dependency to my app, do I need to setup something else to make it work?

**Comment by slavipetrov** [comment]
Hello, @ManuelEMR,

Use the latest version of the library (1.1.5) by adding the dependency in your `build.gradle` file like this `compile 'bg.devlabs.fullscreenvideoview:library:1.1.5'`.

**Comment by ManuelEMR** [comment]
Great thanks!
