### ISSUE TITLE
Change File Option

### ISSUE THREAD

**Issue by galgistmd** [dev-labs-bg/fullscreen-video-view#67]
Hello, the video view is great.
Is there a possibility to add a ChangeFile function ?
There is a ChangeURL one but not for files.
In the default VideoView when you set a new File it's automatically switching and starting to play it, But in your video view when i try to set videoFile when one is already inside it׳s crashing.
thank you very much !

**Comment by slavipetrov** [comment]
Hello, @galgistmd,

There is no such functionality in the library at the moment. I will try to implement it as soon as possible!

**Comment by galgistmd** [comment]
Thank you very much!
Right now when I'm trying to switch it's switching with a glitch.

**Comment by slavipetrov** [comment]
I've released a new version of the library (1.1.6) which supports this functionality now! Enjoy! 🎉

**Comment by galgistmd** [comment]
Hi, just tried to test the new version.
Unfortunately there is an error inflating the class.

 Caused by: android.view.InflateException: Binary XML file line #10: Binary
XML file line #10: Error inflating class
bg.devlabs.fullscreenvideoview.FullscreenVideoView
Caused by: android.view.InflateException: Binary XML file line #10: Error
inflating class bg.devlabs.fullscreenvideoview.FullscreenVideoView

Hope you will be able to solve it, thanks !

**Comment by slavipetrov** [comment]
Hi, I just tested the new version, it's downloaded successfully with Gradle and I am able to use it without any errors.

Are you sure that the version you use is exactly `1.1.6` and the library is downloaded?

**Comment by galgistmd** [comment]
Hi, just tested it again.
version 1.1.5 works perfectly fine, 1.1.6 is not working for me.
The xml preview shows a blank place instead of the video view, unlike in version 1.1.5.

that's the error im getting:

>      Caused by: android.view.InflateException: Binary XML file line #36: Binary XML file line #36: Error inflating class bg.devlabs.fullscreenvideoview.VideoControllerView
>      Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class bg.devlabs.fullscreenvideoview.VideoControllerView
>      Caused by: java.lang.reflect.InvocationTargetException

**Comment by slavipetrov** [comment]
In your XML file, you should use `bg.devlabs.fullscreenvideoview.FullscreenVideoView` not `bg.devlabs.fullscreenvideoview.VideoControllerView`.

Please check if you do it this way and see if you can resolve it.

**Comment by galgistmd** [comment]
Update : switched to LinearLayout and the videoview is working.

I have used the changeVideoFile func. As I told  you until now i have used the changeUrl func and just took the path of the file, It switched the video but not smoothly (with a glitched black screen in between), the changeVideoFile is the same but just taking a file is param. Is there a possibility to update the func in order for it to switch smoothly (just jump to the next video immediately without a black screen in between).

much appreciate, 
thank you very much !

**Comment by slavipetrov** [comment]
I see what I can do about that glitch.

**Comment by galgistmd** [comment]
Thank you very much .

**Comment by slavipetrov** [comment]
Hello, @galgistmd,

Unfortunately, smooth transition is not possible, because the old media player must be stopped and released, also the surface must be recreated in order to play the new provided file/URL.

Closing this.
