### ISSUE TITLE
App Crash on Pre Android 10

### ISSUE THREAD

**Issue by vinaygarg55** [dev-labs-bg/fullscreen-video-view#71]
There is a method named `BlendModeColorFilter()` used in `VideoControllerView`. This method is available only in Android 10 and the app is crashing on versions below Android 10. Need to use `BlendModelColorFilterCompat()`

**Comment by phongbm** [comment]
I have same issue, please fix it.

**Comment by aliotard** [comment]
I confirm this (critical) issue. This bug was introduced in latest version (1.1.6), so downgrading to 1.1.5 fixes it.
